version: '2'

services:

  redis:
    image: redis
    volumes:
     - 'redis:/data'

  platus:
    build: .
    ports:
     - "5001:5001"
    volumes:
     - '.:/platus'
    command: gunicorn -c "platus/config/gunicorn.py" app:application --reload

  celery:
    build: .
    command: celery worker -B -l info -A celery_app.app
    volumes:
      - '.:/platus'
    environment:
      - PLATUS_HOST=platus
      - PLATUS_PORT=5001
      - PLATUS_USER=admin
      - PLATUS_PASS=admin
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis: