version: '2'

services:

  redis:
    image: redis
    volumes:
     - 'redis:/data'

  core:
    image: platus
    ports:
     - "5001:5001"
    volumes:
      - '/tmp/data:/platus/data'

  scheduler:
    image: platus_scheduler
    environment:
      - PLATUS_HOST=core
      - PLATUS_PORT=5001
      - PLATUS_USER=admin
      - PLATUS_PASS=admin
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis: