version: '2'

services:
  platus:
    build: .
    ports:
     - "5001:5001"
    volumes:
     - '.:/platus'
    command: gunicorn -b 0.0.0.0:5001 main:application --reload

  redis:
    image: redis
    ports:
     - "6379:6379"
    volumes:
     - 'redis:/data'

volumes:
  redis: